use_frameworks!
platform :ios,'7.0'

target 'AiryRefreshControl_Example', :exclusive => true do
  pod 'AiryRefreshControl', :path => '../'
end

target 'AiryRefreshControl_Tests', :exclusive => true do
  pod 'AiryRefreshControl', :path => '../'

  
end
